services:
  live.broadcast.command.broadcast:
    class: Martin1982\LiveBroadcastBundle\Command\BroadcasterCommand
    arguments:
        - "@live.broadcast.scheduler"
        - "@logger"
        - "%livebroadcast.event_loop.timer%"
    tags:
        - { name: 'console.command' }

  live.broadcast.command.shelltest:
    class: Martin1982\LiveBroadcastBundle\Command\ShellTestCommand
    tags:
        - { name: 'console.command' }

  live.broadcast.scheduler.commands:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\AbstractSchedulerCommands
      factory: [Martin1982\LiveBroadcastBundle\Broadcaster\SchedulerCommandsDetector, createSchedulerCommands]
      arguments:
          - "@kernel"
          - "%livebroadcast.ffmpeg.log_directory%"

  live.broadcast.starter:
      class: Martin1982\LiveBroadcastBundle\Service\BroadcastStarter
      arguments:
          - "@live.broadcast.stream_input.service"
          - "@live.broadcast.stream_output.service"
          - "@live.broadcast.scheduler.commands"

  live.broadcast.broadcast_manager:
      class: Martin1982\LiveBroadcastBundle\Service\BroadcastManager
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@live.broadcast.channel_api.stack"

  live.broadcast.channel_validator:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelValidatorService
      arguments:
        - "@kernel"
        - "@doctrine.orm.entity_manager"
        - "@validator"

  live.broadcast.scheduler:
      class: Martin1982\LiveBroadcastBundle\Broadcaster\Scheduler
      arguments:
        - "@live.broadcast.channel_validator"
        - "@live.broadcast.starter"
        - "@live.broadcast.broadcast_manager"
        - "@live.broadcast.scheduler.commands"
        - "@logger"
      tags: [{ name: monolog.logger, channel: livebroadcaster }]

# Thumbnail handling
  live.broadcast.thumbnail.uploader:
      class: Martin1982\LiveBroadcastBundle\Service\ThumbnailUploadService
      arguments:
          - '%livebroadcast.thumbnail.upload_directory%'

  live.broadcast.thumbnail.listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\ThumbnailUploadListener
      arguments:
          - '@live.broadcast.thumbnail.uploader'
      tags:
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: postLoad }

# Remote API services
  live.broadcast.stream.announcement.listener:
      class: Martin1982\LiveBroadcastBundle\EventListener\StreamAnnouncementListener
      arguments:
          - '@messenger.routable_message_bus'
          - '@live.broadcast.broadcast_manager'
      tags:
          - { name: doctrine.event_listener, event: postPersist }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: preRemove }

  live.broadcast.message_handler.stream_announcement:
    class: Martin1982\LiveBroadcastBundle\MessageHandler\StreamServiceAnnouncementHandler
    arguments:
      - '@live.broadcast.broadcast_manager'
    tags: [messenger.message_handler]

  live.broadcast.channel_api.stack:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\ChannelApiStack

# Facebook
  live.broadcast.facebook_api.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\FacebookApiService
      public: true
      arguments:
          - "@doctrine.orm.entity_manager"
          - "%livebroadcast.fb.app_id%"
          - "%livebroadcast.fb.app_secret%"
      tags:
          - { name: live.broadcast.api }

# Youtube
  live.broadcast.google_redirect.service:
      class: Martin1982\LiveBroadcastBundle\Service\GoogleRedirectService
      arguments:
          - "@router"
      calls:
        - setRedirectRoute: ['%livebroadcast.yt.redirect_route%']

  live.broadcast.channel_api.client.config.google:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\Config\GoogleConfig
      arguments:
          - "%livebroadcast.yt.client_id%"
          - "%livebroadcast.yt.client_secret%"
  live.broadcast.channel_api.client.config.youtube:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\Config\YouTubeConfig
      arguments:
          - "%router.request_context.scheme%://%router.request_context.host%"
          - "%livebroadcast.thumbnail.web_path%"
  live.broadcast.channel_api.client.google:
      public: true
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\GoogleClient
      arguments:
          - "@live.broadcast.channel_api.client.config.google"
          - "@live.broadcast.google_redirect.service"
          - "@logger"
  live.broadcast.channel_api.client.youtube:
      public: true
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\Client\YouTubeClient
      arguments:
          - "@live.broadcast.channel_api.client.config.youtube"
          - "@live.broadcast.channel_api.client.google"
  live.broadcast.youtube_api.service:
      class: Martin1982\LiveBroadcastBundle\Service\ChannelApi\YouTubeApiService
      public: true
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@logger"
          - "@live.broadcast.channel_api.client.youtube"
      tags:
          - { name: live.broadcast.api }
          - { name: monolog.logger, channel: livebroadcaster }
